name: "upload docker image to AWS ECR"
description: "This action push the docker container to ECR"
inputs:
  image-name:
    description: "the name of the image"
    required: true
  ecr-repository:
    description: "the ECR repository URL"
    required: true
  aws-access-key-id:
    description: "AWS access key ID"
    required: true
  aws-secret-access-key:
    description: "AWS secret access key"
    required: true
  aws-region:
    description: "AWS region"
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region ${{ inputs.aws-region }} | \
        docker login --username AWS --password-stdin ${{ inputs.ecr-repository }}
      shell: bash

    - name: Tag Docker image
      run: docker tag ${{ inputs.image-name }} ${{ inputs.ecr-repository }}/${{ inputs.image-name }}
      shell: bash

    - name: Push to Amazon ECR
      run: docker push ${{ inputs.ecr-repository }}/${{ inputs.image-name }}
      shell: bash
