name: build-docker-new

on:
  push:
    branches:
      - "main"
      - "feature/**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Run tests
        uses: ./.github/actions/node-test-runner
  docker-build-push: 
    runs-on: ubuntu-latest
    needs: test 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: build and run docker container
        uses: ./.github/actions/build-docker
        with:
          image-name: ${{ vars.IMAGE_NAME }}
          container-name: "devopsrunning"
          port-number: "3000:3000"

      - name: Health check
        uses: ./.github/actions/docker-health-check
        with:
          container-name: "devopsrunning"
          url-to-check: "http://localhost:3000/health"

      - name: Upload to ECR
        uses: ./.github/actions/upload-to-ecr
        with:
          image-name: ${{ vars.IMAGE_NAME }}
          ecr-repository: ${{ vars.ECR_REPOSITORY }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
